// small_shop_mobile/src/views/login/index.vue
<template>
  <div class="login">
    <div class="contain">
      <div class="title">微商城</div>
      <van-form @submit="onSubmit" class="from">
        <van-cell-group inset>
          <van-field
            v-model="username"
            name="username"
            label="账号"
            placeholder="账号"
            :rules="[{ required: true, message: '请填写账号' }]"
          />
          <van-field
            v-model="password"
            type="password"
            name="password"
            label="密码"
            placeholder="密码"
            :rules="[{ required: true, message: '请填写密码' }]"
          />
        </van-cell-group>
        <div style="margin: 16px">
          <van-button round block type="danger" native-type="submit">
            登录
          </van-button>
        </div>
        <div class="footer">Copyright © 2021-{{ new Date().getFullYear() }}  微商城 </div>
      </van-form>
    </div>
  </div>
</template>

<script setup lang="ts">
  import {LoginForm} from "@/types/login"
  import {login} from "@/api/request"
import { Toast } from "vant";
const router = useRouter()
const route = useRoute()
const username = ref("");
const password = ref("");

const onSubmit =async (values:LoginForm) => {
  const {data:res} = await login(values)
  if(res.code===403) return Toast.fail("账号不存在")
  if(res.code===404) return Toast.fail("账号或密码不存在")
  Toast.success("登录成功")
  localStorage.setItem("userInfo",JSON.stringify(res.data[0]))
  localStorage.setItem("userId",res.data[0].userId)
  const path= localStorage.getItem("path")
  if(path){
    router.replace(path)
    localStorage.removeItem("path")
  }else{
    router.replace("/shop/profile")
  }
};



onUnmounted(()=>{
  const path= localStorage.getItem("path")
  if(!localStorage.getItem("userInfo")){
    router.replace("/")
    if(path){
      router.replace(path)
    }
  }
})
</script>

<style lang="less" scoped>
.login {
  width: 100vw;
  height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
  .contain {
    width: 85%;
    height: 22.25rem;
    box-shadow: 0 0 1.25rem #eee;
    border-radius: .625rem;
    text-align: center;
    padding: 2rem 1.05rem;
    box-sizing: border-box;
    .title {
      font-size: 1.875rem;
    }
    .from{
      width: 100%;
      margin-top: 1.875rem;
    }
    .footer{
      margin-top: 2rem;
      font-size: 0.6rem;
    }
  }
}
</style>

// small_shop_back/src/views/login/index.jsx
import React, { useEffect } from 'react'
import style from "./style/index.module.scss"
import { Button, Form, Input,message } from 'antd';
import {useNavigate} from "react-router-dom"
import {setLogin} from "../../api/request"
const layout = {
  labelCol: {
    span: 5,
  },
  wrapperCol: {
    span: 16,
  },
};
const tailLayout = {
  wrapperCol: {
    offset: 5,
    span: 16,
  },
};

export default function Login() {
  const [form] = Form.useForm();
  const navigate = useNavigate()

  useEffect(()=>{
    const token = sessionStorage.getItem("token")
    if(token) return navigate("/")
  },[])


  const onFinish = async(values) => {
    const {data:res} = await setLogin(values)
    if(res.code==400) return message.error("该账号未进行注册")
    if(res.code==404) return message.error("密码错误")
    sessionStorage.setItem("token",res.token)
    sessionStorage.setItem("secretKey",res.secret)
    message.success("登录成功")
    navigate("/small-shop/statistics")
    window.location.reload()
  };

  const onReset = () => {
    form.resetFields();
  };

  return (
    <div className={style.box}>
      <div className={style.content}>
        <h1>微商城后台管理</h1>
        <Form className={style.form} {...layout} form={form} name="control-hooks" onFinish={onFinish}>
      <Form.Item
        name="username"
        className={style.item}
        label="账号"
        rules={[
          {
            required: true,
            message:"管理员账号不能为空"
          },
        ]}
      >
        <Input placeholder='请输入管理员账号' />
      </Form.Item>
      <Form.Item
      className={style.item}
        name="password"
        label="密码"
        rules={[
          {
            required: true,
            message:"密码不能为空"
          },
        ]}
      >
        <Input.Password placeholder='请输入密码' />
      </Form.Item>
    
       
      <Form.Item className={style.item} {...tailLayout}>
        <Button  className={style.btn} type="dashed" htmlType="submit">
          登录
        </Button>
      </Form.Item>
    </Form>
      </div>
    <div className={style.footer}>Copyright © 2021-{new Date().getFullYear()} small-shop 微商城 All Rights Reserved</div>
    </div>
  )
}
